# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import tkinter as tk
from gui.controller import Controller
# from gui.gui1 import init_2
from db import db

if __name__ == "__main__":
    # DB Connection
    db.connect()
    # 사용 방법 정리, 추후 삭제
    #result = db.getRandomStyle(10, '캐주얼')[0]
    #db.saveMachingStyle('2024-06-14', 10, result.get('id'), result.get('bottom.id'))
    #result = db.getStyleList()

    # Main window constructor
    root = tk.Tk()  # Make temporary window for app to start
    # root.withdraw()  # WithDraw the window
    app = Controller(root)
    # mainWindow()

    root.mainloop()
